name: Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git pull
        run: git pull

      - name: Install dependencies
        run: npm install

      - name: Restart service
        run: |
          # Reiniciar el servicio usando systemctl con el usuario deployuser
          sudo -u deployuser /bin/systemctl restart iescrow.service