name: Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PM2 globally
        run: sudo npm install -g pm2

      - name: Install dependencies
        run: npm install

      - name: Start or restart PM2 process
        run: |
          pm2 restart iescrow